"""Add reserved_stock and reference_type

Revision ID: 138ecb4e5d54
Revises: 23656acd68dc
Create Date: 2026-04-06 11:51:47.936924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138ecb4e5d54'
down_revision: Union[str, Sequence[str], None] = '23656acd68dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('movement_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_stock', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_check_constraint('chk_product_reserved_stock', 'reserved_stock >= 0')
        batch_op.create_check_constraint('chk_product_availability', 'stock_actual >= reserved_stock')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('reserved_stock')

    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.alter_column('movement_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('reference_type')

    # ### end Alembic commands ###
