"""Init

Revision ID: 23656acd68dc
Revises: 
Create Date: 2026-04-06 11:47:40.673639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23656acd68dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('products_created', sa.Integer(), nullable=True),
    sa.Column('products_updated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('csv_upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_csv_upload_id'), ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('departments_count', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('imagen_frontis', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_name'), ['name'], unique=True)

    op.create_table('dispatch_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_batch_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_batch_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_batch_id'), ['id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_csv_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('is_dynamic', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('stock_actual >= 0', name='chk_product_stock_actual'),
    sa.ForeignKeyConstraint(['source_csv_id'], ['csv_upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_source_csv_id'), ['source_csv_id'], unique=False)

    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=150), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_id'), ['id'], unique=False)

    op.create_table('building_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='chk_building_inventory_quantity'),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'product_id', name='uq_building_inventory_product')
    )
    with op.batch_alter_table('building_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_inventory_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_inventory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_inventory_product_id'), ['product_id'], unique=False)

    op.create_table('consumption_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('quantity_consumed', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumption_log_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumption_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumption_log_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumption_log_reported_by_id'), ['reported_by_id'], unique=False)

    op.create_table('dispatch_batch_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('total_quantity > 0', name='chk_dispatch_batch_item_quantity'),
    sa.ForeignKeyConstraint(['batch_id'], ['dispatch_batch.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'product_id', name='uq_dispatch_batch_item_product')
    )
    with op.batch_alter_table('dispatch_batch_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_batch_item_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_batch_item_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_batch_item_product_id'), ['product_id'], unique=False)

    op.create_table('inventory_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movement_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_reference_id'), ['reference_id'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_id'), ['id'], unique=False)
        batch_op.create_index('ix_unique_building_draft_order', ['building_id'], unique=True, sqlite_where=sa.text("status = 'draft'"), postgresql_where=sa.text("status = 'draft'"))

    op.create_table('purchase_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='chk_purchase_item_quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_item_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_item_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_item_purchase_id'), ['purchase_id'], unique=False)

    op.create_table('dispatch_batch_orders',
    sa.Column('dispatch_batch_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_batch_id'], ['dispatch_batch.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('dispatch_batch_id', 'order_id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('nombre_producto_snapshot', sa.String(length=100), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='chk_order_item_quantity'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_id'))

    op.drop_table('order_item')
    op.drop_table('dispatch_batch_orders')
    with op.batch_alter_table('purchase_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_item_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_item_id'))

    op.drop_table('purchase_item')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_building_draft_order', sqlite_where=sa.text("status = 'draft'"), postgresql_where=sa.text("status = 'draft'"))
        batch_op.drop_index(batch_op.f('ix_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_order_building_id'))

    op.drop_table('order')
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movement_reference_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_created_at'))

    op.drop_table('inventory_movement')
    with op.batch_alter_table('dispatch_batch_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_batch_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_batch_item_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_batch_item_batch_id'))

    op.drop_table('dispatch_batch_item')
    with op.batch_alter_table('consumption_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumption_log_reported_by_id'))
        batch_op.drop_index(batch_op.f('ix_consumption_log_product_id'))
        batch_op.drop_index(batch_op.f('ix_consumption_log_id'))
        batch_op.drop_index(batch_op.f('ix_consumption_log_building_id'))

    op.drop_table('consumption_log')
    with op.batch_alter_table('building_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_inventory_product_id'))
        batch_op.drop_index(batch_op.f('ix_building_inventory_id'))
        batch_op.drop_index(batch_op.f('ix_building_inventory_building_id'))

    op.drop_table('building_inventory')
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_created_at'))

    op.drop_table('purchase')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_source_csv_id'))
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_id'))

    op.drop_table('product')
    with op.batch_alter_table('dispatch_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_batch_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_batch_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_batch_created_at'))

    op.drop_table('dispatch_batch')
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_name'))
        batch_op.drop_index(batch_op.f('ix_building_id'))
        batch_op.drop_index(batch_op.f('ix_building_admin_id'))

    op.drop_table('building')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('csv_upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_csv_upload_id'))

    op.drop_table('csv_upload')
    # ### end Alembic commands ###
