"""add_building_id_to_inventory_movement

Revision ID: 73dc54a4bbd8
Revises: 138ecb4e5d54
Create Date: 2026-04-06 12:14:06.813521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73dc54a4bbd8'
down_revision: Union[str, Sequence[str], None] = '138ecb4e5d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_movement_building_id'), ['building_id'], unique=False)
        batch_op.create_foreign_key('fk_inventory_movement_building', 'building', ['building_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_movement_building', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_movement_building_id'))
        batch_op.drop_column('building_id')

    # ### end Alembic commands ###
